apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nv2u
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0037-tenant/tkrw-pr714-0075-0037-app/devfile-sample-nv2u@sha256:adfb3f6ea51454924880ff8f8d4ff309764a4be4d0809182a6ec144b9bae2fc1
        name: my-nodejs
        resources: {}
status: {}
